// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBttFJ0LQ8iG3IVUV9JTaRuZD7e3Eu7NXg',
    appId: '1:267088555089:android:61565453d226f5cace1c70',
    messagingSenderId: '267088555089',
    projectId: 'flutter-prep-10a1f',
    databaseURL: 'https://flutter-prep-10a1f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-10a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqu0r66gEmcYGVwTmJXlWjneW2CpRU0bU',
    appId: '1:267088555089:ios:a2b39aa981af28c4ce1c70',
    messagingSenderId: '267088555089',
    projectId: 'flutter-prep-10a1f',
    databaseURL: 'https://flutter-prep-10a1f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-10a1f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
